### ISSUE TITLE
Bundle . JS not found

### ISSUE THREAD

**Issue by mmgilani** [htoor91/ChitChat#1]
Hey, I saw your very nice chat app, but I wasn't able to get it running..

I was getting this error in my browser :

GET http://localhost:3000/js/bundle.js 404 (Not Found)

Refused to execute script from 'http://localhost:3000/js/bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.

Hope you know how to fix this ?

Thank you very much

**Comment by htoor91** [comment]
@mmgilani Hey! If you wanna run it on your local, here are the steps:

1. Clone it on your machine
2. In terminal cd to your directory, run 'npm install' to install all packages
3. In another terminal tab same directory, run 'mongod' to run the DB services. Might need to setup mongoDB if you haven't already
4. In another terminal tab, run 'webpack -w' to create the bundle
5. In another tab, run 'npm start' to start the server on port 3000

**Comment by mmgilani** [comment]
Hey @htoor91 

I am not able to complete step 4)
When I do the command 'webpack-w', I get this:

The CLI moved into a separate package: webpack-cli
Would you like to install webpack-cli? (That will run npm install -D webpack-cli) (yes/NO)

And if I choose yes:

{ Error: Cannot find module 'webpack-cli'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at runCommand.then.result (/usr/local/lib/node_modules/webpack/bin/webpack.js:62:14)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7) code: 'MODULE_NOT_FOUND' }

Do you know the solution for this ?

**Comment by htoor91** [comment]
@mmgilani  Do you have webpack 4? Then I think this is your issue https://stackoverflow.com/questions/49092291/the-cli-moved-into-a-separate-package-webpack-cli

just run 'npm install webpack-cli --save-dev'

**Comment by mmgilani** [comment]
@htoor91 Yes you were right, thankyou very much !
